accessing
error: anException
	error := anException